server:
  port: 8080
  servlet:
    context-path: /reservation
    

spring:
  security: 
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/679145ad-f827-42d8-b45e-720324e5d2a2/v2.0
          jwk-set-uri: https://login.microsoftonline.com/679145ad-f827-42d8-b45e-720324e5d2a2/discovery/v2.0/keys


# Actuator Properties
management:
  endpoints:
    web:
      exposure:
        include:
        - loggers
        - health
        - info
        - metrics
        - env
  endpoint:
    env:
      enabled: true
    loggers:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true